@Host = https://localhost:40443

GET {{Host}}/api/board-games
Accept: application/json

###

GET {{Host}}/api/board-games?pageIndex=0&pageSize=5
Accept: application/json

###

GET {{Host}}/api/board-games?pageIndex=1&pageSize=5
Accept: application/json

###

GET {{Host}}/api/board-games?pageIndex=2&pageSize=5
Accept: application/json

###

PUT {{Host}}/api/seed
Accept: application/json

###

